# Generated by Django 5.2.7 on 2025-10-16 07:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('project', 'Project'), ('concept', 'Concept'), ('practice', 'Practice Exercise')], max_length=20)),
                ('estimated_hours', models.IntegerField(default=10)),
                ('completed', models.BooleanField(default=False)),
                ('dependencies', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learn.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(default='free', max_length=20)),
                ('estimated_time', models.IntegerField(default=60)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learn.roadmaptask')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('technology_domain', models.CharField(blank=True, choices=[('web', '🌐 Web Development'), ('mobile', '📱 Mobile Development'), ('data', '📊 Data Science'), ('ai', '🤖 AI & Machine Learning'), ('cloud', '☁️ Cloud Computing'), ('cyber', '🔒 Cybersecurity')], max_length=20)),
                ('programming_language', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('php', 'PHP'), ('ruby', 'Ruby'), ('csharp', 'C#'), ('go', 'Go'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('r', 'R'), ('sql', 'SQL'), ('julia', 'Julia'), ('scala', 'Scala'), ('cpp', 'C++'), ('c', 'C'), ('none', 'Not Sure / Start with Basics')], default='none', max_length=50)),
                ('framework', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow'), ('pandas', 'Pandas'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('express', 'Express.js'), ('nextjs', 'Next.js'), ('nestjs', 'NestJS'), ('spring', 'Spring Boot'), ('hibernate', 'Hibernate'), ('laravel', 'Laravel'), ('rails', 'Ruby on Rails'), ('aspnet', 'ASP.NET'), ('flutter', 'Flutter'), ('none', 'No Framework / Learn Language First')], default='none', max_length=50)),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', '🚀 Beginner - Just starting out'), ('intermediate', '⚡ Intermediate - Some experience'), ('advanced', '🎯 Advanced - Comfortable with coding')], max_length=15)),
                ('learning_goals', models.TextField(blank=True)),
                ('time_commitment', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_completed', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='learn.userprofile'),
        ),
    ]
